---
dotfiles_alsa_pkg_conflict_items:
  - pulseaudio

dotfiles_alsa_pkg_items:
  - alsa-utils
  - alsa-plugins

dotfiles_awm_pkg_items:
  - awesome
  - picom
  - feh
  - light
  - papirus-icon-theme
  - xss-lock
  - inotify-tools
  - scrot

dotfiles_awm3_pkg_items:
  - awesome
  - picom
  - feh
  - light
  - papirus-icon-theme
  - xss-lock
  - inotify-tools
  - maim
  - app-misc/jq
  - net-misc/curl

dotfiles_betterlockscreen_pkg_items:
  - x11-misc/betterlockscreen

dotfiles_emacs_pkg_items:
  - ripgrep
  - sys-apps/findutils
  - sys-apps/fd
  - app-misc/jq
  - htmltidy
  - luacheck
  - emacs
# TODO 2023-12 dont compile with musl, try later (because ghc (haskell dep))
#  - shellcheck

dotfiles_files_browser_alsa_pkg_items:
  - xfce-base/thunar
  - xfce-base/tumbler

dotfiles_files_browser_pulse_pkg_items:
  - gnome-extra/nemo

dotfiles_files_browser_conflict_pkg_items:
  - bat
  - ffmpegthumbnailer
  - ueberzug
  - vifm
  - w3m
  - xdotool

dotfiles_files_browser_pkg_items:
  - mpv
  - app-misc/yazi
  - poppler
  - zathura
  - zathura-pdf-mupdf

dotfiles_foot_pkg_items:
  - gui-apps/foot

dotfiles_kitty_pkg_items:
  - x11-terms/kitty

dotfiles_gpu_intel_gen7_conflict_pkg_items:
  - libva-intel-media-driver

# https://wiki.gentoo.org/wiki/Intel_Graphics#VAAPI
dotfiles_gpu_intel_gen7_pkg_items:
  - media-libs/mesa
  - libva-intel-driver

dotfiles_gpu_intel_pkg_items:
  - sys-kernel/linux-firmware
  - libva-intel-media-driver
  - media-libs/vulkan-loader

dotfiles_gpu_nouveau_conflict_pkg_items:
  - x11-drivers/nvidia-drivers

dotfiles_gpu_nouveau_pkg_items:
  - sys-firmware/nvidia-firmware

dotfiles_mpd_pkg_items:
  - cava
  - media-sound/mpd
  - media-sound/mpc
  - ncmpcpp

dotfiles_neomutt_conflict_pkg_items:
  - mutt
  - msmtp
  - fdm

dotfiles_neomutt_pkg_items:
  - neomutt
  - net-mail/isync

dotfiles_neovim_conflict_pkg_items:
  - vim

dotfiles_neovim_pkg_items:
  - neovim
  - sys-apps/fd
  - ripgrep
  - fzf
  - tmux
  - net-libs/nodejs
  - app-admin/ansible-lint
  - sys-apps/the_silver_searcher

dotfiles_pulseaudio_pkg_items:
  - pulseaudio

dotfiles_swayfx_pkg_items:
  - light
  - net-misc/curl
  - inotify-tools
  - swaybg
  - imagemagick
  - imv
  - app-misc/jq
  - playerctl
  - wl-clipboard
  - gui-apps/grim
  - net-wireless/iwd
  - gui-apps/eww
  - gui-wm/swayfx
  - media-gfx/chafa
  - mpv-mpris
  - mpd-mpris
  - acct-group/seat
  - seatd
  - x11-misc/dunst
  - gui-apps/swaylock
  - gui-apps/swayidle
  - gui-apps/wlr-randr

dotfiles_swayfx_add_to_group:
  - seat
  - video

dotfiles_swayfx_services:
  - seatd

dotfiles_xorg_pkg_items:
  - xorg-server
  - xinit
  - x11-misc/xclip
  - xf86-input-libinput

dotfiles_vim_conflict_pkg_items:
  - app-editors/neovim
  - app-editors/gvim

dotfiles_vim_pkg_items:
  - app-editors/vim

dotfiles_wezterm_pkg_items:
  - wezterm

dotfiles_xst_pkg: xst

dotfiles_zsh_path: /bin/zsh
dotfiles_zsh_pkg_items:
  - zsh
  - app-shells/starship
  - net-misc/yt-dlp
